- name: download couchbase server
  get_url: url=http://packages.couchbase.com/releases/4.0.0/couchbase-server-enterprise-4.0.0-centos7.x86_64.rpm
           dest=/home/vagrant/couchbase-server.rpm

- name: install couchbase server
  sudo: yes
  yum: name=/home/vagrant/couchbase-server.rpm state=present

- name: start service
  service: name=couchbase-server state=started
